# Generated by Django 4.2.11 on 2026-07-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение к вопросу', null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False, help_text='Разрешить выбор нескольких вариантов'),
        ),
    ]
