# Generated by Django 5.0.14 on 2026-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
